// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyrEuCFt8b2gO1STNIp9MNgNatUmu4RQ',
    appId: '1:627571054534:web:b3dcd722912580a518c4c7',
    messagingSenderId: '627571054534',
    projectId: 'saveeplate',
    authDomain: 'saveeplate.firebaseapp.com',
    storageBucket: 'saveeplate.firebasestorage.app',
    measurementId: 'G-E2HR2VSH9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtas3gdyi3mn_wNpk9HQietnVOUxtwv4',
    appId: '1:627571054534:android:d83712a5e72cffd718c4c7',
    messagingSenderId: '627571054534',
    projectId: 'saveeplate',
    storageBucket: 'saveeplate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZgISxPIbJODjjL13WvYnR8qIggTbeVc',
    appId: '1:627571054534:ios:1e6341b6ad50bd7f18c4c7',
    messagingSenderId: '627571054534',
    projectId: 'saveeplate',
    storageBucket: 'saveeplate.firebasestorage.app',
    iosBundleId: 'com.example.saveplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZgISxPIbJODjjL13WvYnR8qIggTbeVc',
    appId: '1:627571054534:ios:1e6341b6ad50bd7f18c4c7',
    messagingSenderId: '627571054534',
    projectId: 'saveeplate',
    storageBucket: 'saveeplate.firebasestorage.app',
    iosBundleId: 'com.example.saveplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIyrEuCFt8b2gO1STNIp9MNgNatUmu4RQ',
    appId: '1:627571054534:web:7847baba7a9775d918c4c7',
    messagingSenderId: '627571054534',
    projectId: 'saveeplate',
    authDomain: 'saveeplate.firebaseapp.com',
    storageBucket: 'saveeplate.firebasestorage.app',
    measurementId: 'G-18Q3E97TT8',
  );

}