// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyc6KXt-ky8zAlG3hQ9ObTHwpoMIgeyJE',
    appId: '1:443285938782:web:032c345e0746419929cacf',
    messagingSenderId: '443285938782',
    projectId: 'save-plate',
    authDomain: 'save-plate.firebaseapp.com',
    storageBucket: 'save-plate.firebasestorage.app',
    measurementId: 'G-MG7L4FZ8R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLePPbGaBW5vyDkSFpSWjEYzdLCV8rVMo',
    appId: '1:443285938782:android:6629094fdf5f770e29cacf',
    messagingSenderId: '443285938782',
    projectId: 'save-plate',
    storageBucket: 'save-plate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkc2c3h1FhmgOJ19aEp9mTBGCGgpaSQ9I',
    appId: '1:443285938782:ios:5b8b533b40d6ea4929cacf',
    messagingSenderId: '443285938782',
    projectId: 'save-plate',
    storageBucket: 'save-plate.firebasestorage.app',
    iosBundleId: 'com.example.saveplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkc2c3h1FhmgOJ19aEp9mTBGCGgpaSQ9I',
    appId: '1:443285938782:ios:5b8b533b40d6ea4929cacf',
    messagingSenderId: '443285938782',
    projectId: 'save-plate',
    storageBucket: 'save-plate.firebasestorage.app',
    iosBundleId: 'com.example.saveplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyc6KXt-ky8zAlG3hQ9ObTHwpoMIgeyJE',
    appId: '1:443285938782:web:2c08637045fdce1f29cacf',
    messagingSenderId: '443285938782',
    projectId: 'save-plate',
    authDomain: 'save-plate.firebaseapp.com',
    storageBucket: 'save-plate.firebasestorage.app',
    measurementId: 'G-FDWC6S6QNV',
  );
}
